AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Style/Documentation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/WordArray:
  Enabled: true
